config/routes.rb
IrippleCloudbuy::Application.routes.draw do

  root to: 'sessions#new'

  resources :suppliers do
    member do
      get :activate
      get :products
      get :purchase_orders
      get :activate_product
      post :assigner
      post :unassigner
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned' 
      get :purchase_orders
    end
    collection do
      get :get_product_categories      
    end
  end

  resources :branches do
    member do
      post :assigner
      post :unassigner
      post :getSched
      post :assign_default_supplier
      get  :get_products_duplicate_assign  
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned'
    end

    collection do
      get   :get_branches_of_supplier
    end
  end

  resources :purchase_orders, path: '/purchase-orders' do
    member do
      post   :add_po_line
      post   :del_po_line
      get    :get_prod_to_add 
      get   :purchase_order_lines, path: '/purchase-order-lines'
      post  :po_line_commit, path: '/po-line-commit'
      post  :add_remarks, path: '/add-remarks'
    end

    collection do
      post  :update_line_items, path: '/update-line-items'
      post  :trigger_manual_po, path: '/manual-po'
      post  :copy_po
    end
  end

  resources :purchase_order_lines, path: '/purchase-order-lines' do    
    collection do
      get  :order_to_suppliers, path: '/order-to-suppliers'
      post :transfer_to_supplier, path: '/transfer-to-supplier'
      post :commit_transfer_to_supplier, path: '/commit-transfer-to-supplier'
    end
  end

  resources :dashboards do    
    collection do
      get :supplier_index
      post :upload
    end
  end

  resources :users do
    member do
      get   :activate
      get   :assigned_suppliers
      get   :unassigned_suppliers
      get   :recover_password, path: '/recover-password'
      post  :assigner
      post  :unassigner
    end
    collection do
      get   :view_api_key, path: '/view-api-key'
      get   :forget_password, path: '/forget-password'
      get   :change_password, path: '/change-password'
      put   :change_password, path: '/change-password'
      post  :send_password
      post  :reset_password
    end
  end

  resources :sessions do
    collection do
      post :locate_subdomain
    end
  end

  namespace :admin do
    get '' => 'sessions#new'
    resources :sessions
    resources :dashboards
    resources :accounts do
      member {
        get :run_indexing
      }
    end
    resources :users    
  end

  resources :transactions do
    collection {
      get :historical_data, path: '/historical-data'
      get :sales_and_inventory_data, path: '/sales-and-inventory'
      get :inventory_sales_ratio, path: '/inventory-sales-ratio'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :purchase_orders, only: [:index,:show, :received], path: '/purchase_orders' do
        collection do
          post 'received'
        end
      end
    end
    namespace :v2 do
      resources :purchase_orders, only: [:index], path: '/purchase_orders'
    end
  end

  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get


end

app/models/account.rb
require 'csv'
require 'pathname'

include GeneratePurchaseOrder::Base
include FastImport::Base
include TestImport::Base
include IndexData::Base

class Account < ActiveRecord::Base

  validates_uniqueness_of :subdomain  

  attr_accessible :name, :subdomain, :last_data_index, :index_status
  after_create    :assign_directory
  after_create    :create_API_key

  attr_accessible :users_attributes

  has_many :product_categories
  has_many :active_branches, class_name: Branch, conditions: { status: 'A' }
  has_many :branches
  has_many :branch_supplier_configurations
  has_many :companies
  has_many :users, dependent: :destroy
  has_many :products
  has_many :product_units, class_name:  Product
  has_many :suppliers
  has_many :sales
  has_many :purchase_orders
  has_many :purchase_order_lines
  has_many :loading_logs
  has_many :branch_products
  has_many :transactions
  has_many :supplier_products
  has_one  :account_configuration
  has_many :ownerships
  has_one :api_key


  accepts_nested_attributes_for :users

  def account_dir
    #Rails.root.join('file-server').join("#{id}")
    Rails.root.join('test').join('test_data')
  end

  def archives_dir
    account_dir.join('archives')
  end

  def uploads_dir
    account_dir.join('uploads')
  end

  def errors_dir
    account_dir.join('errors')
  end

  # create directory after user signed up
  # for test purposes only

  def assign_directory
    directoryUpload = File.join(Rails.root, 'file-server', "#{self.id}", 'uploads')
    directoryArchive = File.join(Rails.root, 'file-server', "#{self.id}", 'archive')
    FileUtils.mkdir_p(directoryUpload)
    FileUtils.mkdir_p(directoryArchive)
  end

  def create_API_key
    APIKey.create(account_id: self.id)
  end

end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController

  layout 'admin'
  before_filter :check_session

  def index
    @merchants = Account.all
  end

  def new
    @merchant = Account.new
    @merchant.users.build
  end

  def create
    @merchant = Account.new(params[:account])
    if @merchant.save
      password = params[:account][:users_attributes]['0'][:password]
      save_owner_privileges
      MerchantMailer.welcome_mailer(@merchant.users.first, @merchant.subdomain, password).deliver
      redirect_to admin_accounts_path, notice: 'New Merchant has been successfully added!'
    else
      render 'new'
    end
  end

  def run_indexing
    merchant = Account.find(params[:id])    
    merchant.update_attributes(index_status: :in_progress)
    exec_rake :run_data_indexing, account_id: merchant.id
    redirect_to admin_accounts_path, notice: "Data indexing started successfully!"
  end

  def show
    @merchant = Account.find(params[:id])
  end

  def save_owner_privileges
    role_columns = [:user_id, :name]
    roles = []
    roles << [@merchant.users.first.id, 'rpo']
    roles << [@merchant.users.first.id, 'apo']
    roles << [@merchant.users.first.id, 'cpo']
    roles << [@merchant.users.first.id, 'epo']
    roles << [@merchant.users.first.id, 'ssu']
    roles << [@merchant.users.first.id, 'spr']

    Role.import(role_columns, roles)
  end

  private

  def check_session
    if current_user.nil? || current_user.role != 'cb_admin'
      redirect_to new_admin_session_path, alert: 'Session expired. Please re login!'
    end
  end

end

app/views/admin/accounts/index.html.haml
.col-xs-12.padding-0
  .col-xs-6.padding-0
    %h2 Merchant Accounts
  .col-xs-6.padding-0
    %h2.text-right
      = link_to 'Add Another Account', new_admin_account_path, class: 'btn btn-success'
%table.table-global.table
  %tr
    %th No
    %th Merchant Name
    %th Subdomain
    %th Date Registered
    %th Last Index Date
    %th{width: '140'} Action
  - no = 0
  - @merchants.each do |merchant|
    %tr
      %td= no += 1
      %td= link_to merchant.name, admin_account_path(merchant)
      %td= merchant.subdomain
      %td= merchant.created_at
      %td= merchant.last_data_index
      %td
        - if merchant.index_status == 'done'
          = link_to 'Index data', run_indexing_admin_account_path(merchant), class: 'btn btn-primary btn-md'
            
        - else  
          %span.btn.btn-primary.bth-md#yo{'data-loading-text'=>'Indexing data...'}            
            :javascript
              $("#yo").button('loading');

app/views/admin/accounts/new.html.haml
.col-xs-12.col-lg-5
  %h2 Add New Merchant Account
  = form_for @merchant, url: url_for(action: :create) do |f|
    .form-group
      %label Merchant Name
      = f.text_field :name, class: 'form-control'
    .form-group
      %label Short Name
      = f.text_field :subdomain, class: 'form-control'

    = f.fields_for :users do |u|
      .form-group
        %label First Name
        = u.text_field :first_name, class: 'form-control'
        = u.hidden_field :role, class: 'hidden', value: :owner
      .form-group
        %label Last Name
        = u.text_field :last_name, class: 'form-control'
      .form-group
        %label Email
        = u.email_field :email, class: 'form-control'
      .form-group
        %label Password
        = u.text_field :password, class: 'form-control'

    .form-group
      = f.submit 'Submit', class: 'btn btn-primary btn-sm'
      = button_tag 'Reset', type: :reset, class: 'btn btn-danger btn-sm'
.col-xs-12.col-lg-1
.col-xs-12.col-lg-5
  %br
  %br
  %br
  %br
  - if @merchant.errors.any?
    - @merchant.errors.each do |attrib, msg|
      .alert-dismissible.alert.alert-danger{role: :alert}
        %span.close{'data-dismiss' => "alert"}
          %span{'aria-hidden'=>'true'} &times;
        %strong= attrib.to_s.titleize.gsub('Users.', '')
        = "#{msg}"

app/views/admin/accounts/show.html.haml
- @users = User.where(:account_id => @merchant.id)
.col-xs-12.padding-0
  .col-lg-6.padding-0
    %h2 List of Users
%table.table-global.table
  %tr
    %th No
    %th First Name
    %th Last Name
    %th Email Address
    %th Date Registered
    %th Role
    %th Status
  - no = 0
  - @users.each do |user|
    %tr
      %td= no += 1
      %td= user.first_name
      %td= user.last_name
      %td= user.email
      %td= user.created_at.strftime('%m-%d-%Y %I:%M %p')
      %td= user.role
      %td= user.status