config/routes.rb
IrippleCloudbuy::Application.routes.draw do

  root to: 'sessions#new'

  resources :suppliers do
    member do
      get :activate
      get :products
      get :purchase_orders
      get :activate_product
      post :assigner
      post :unassigner
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned' 
      get :purchase_orders
    end
    collection do
      get :get_product_categories      
    end
  end

  resources :branches do
    member do
      post :assigner
      post :unassigner
      post :getSched
      post :assign_default_supplier
      get  :get_products_duplicate_assign  
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned'
    end

    collection do
      get   :get_branches_of_supplier
    end
  end

  resources :purchase_orders, path: '/purchase-orders' do
    member do
      post   :add_po_line
      post   :del_po_line
      get    :get_prod_to_add 
      get   :purchase_order_lines, path: '/purchase-order-lines'
      post  :po_line_commit, path: '/po-line-commit'
      post  :add_remarks, path: '/add-remarks'
    end

    collection do
      post  :update_line_items, path: '/update-line-items'
      post  :trigger_manual_po, path: '/manual-po'
      post  :copy_po
    end
  end

  resources :purchase_order_lines, path: '/purchase-order-lines' do    
    collection do
      get  :order_to_suppliers, path: '/order-to-suppliers'
      post :transfer_to_supplier, path: '/transfer-to-supplier'
      post :commit_transfer_to_supplier, path: '/commit-transfer-to-supplier'
    end
  end

  resources :dashboards do    
    collection do
      get :supplier_index
      post :upload
    end
  end

  resources :users do
    member do
      get   :activate
      get   :assigned_suppliers
      get   :unassigned_suppliers
      get   :recover_password, path: '/recover-password'
      post  :assigner
      post  :unassigner
    end
    collection do
      get   :view_api_key, path: '/view-api-key'
      get   :forget_password, path: '/forget-password'
      get   :change_password, path: '/change-password'
      put   :change_password, path: '/change-password'
      post  :send_password
      post  :reset_password
    end
  end

  resources :sessions do
    collection do
      post :locate_subdomain
    end
  end

  namespace :admin do
    get '' => 'sessions#new'
    resources :sessions
    resources :dashboards
    resources :accounts do
      member {
        get :run_indexing
      }
    end
    resources :users    
  end

  resources :transactions do
    collection {
      get :historical_data, path: '/historical-data'
      get :sales_and_inventory_data, path: '/sales-and-inventory'
      get :inventory_sales_ratio, path: '/inventory-sales-ratio'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :purchase_orders, only: [:index,:show, :received], path: '/purchase_orders' do
        collection do
          post 'received'
        end
      end
    end
    namespace :v2 do
      resources :purchase_orders, only: [:index], path: '/purchase_orders'
    end
  end

  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get


end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  attr_accessible :account_id, :branch_id, :buyer_id, :supplier_id,
                  :computation_end_date, :computation_options, :computation_start_date,
                  :date, :manager_id, :status, :overall_discount, :total_po_cost,
                  :mother_ref_no, :reference, :order_status, :due_date, :cancellation_date, :created_by_id,
                  :total_units, :total_quantity, :gross_amount, :total_item_discount,
                  :grand_total, :product_category_id, :cancellation_date,
                  :action_state, :reviewed_by_id, :voided_by_id, :void_reason, :approved_by_id, :assigned_to_user_id,
                  :current_viewer_id, :edit_expiration, :supplier_support_discount, :supplier_terms

  # validates :status, inclusion: { in: %w(Approved Voided Reviewed New) }
  validates_uniqueness_of :reference

  scope :unapprove_po, where(:status => 'S')
  scope :approved_po, where(:status => 'A')
  scope :voided_po, where(:status => 'V')
  scope :for_today, lambda{|s| where('(updated_at between ? and ? or status = ?) and supplier_id IN (?)', Date.today.beginning_of_day, Date.tomorrow.end_of_day, 'S', s)}

  belongs_to :account
  belongs_to :branch
  belongs_to :supplier
  belongs_to :product_category
  belongs_to :user  

  has_many :purchase_order_lines, :foreign_key => :purchase_order_id, :primary_key => :reference, dependent: :destroy
  has_one  :po_number

  belongs_to :created_by,  :class_name => User, :foreign_key => :created_by_id
  belongs_to :reviewed_by, :class_name => User, :foreign_key => :reviewed_by_id
  belongs_to :approved_by, :class_name => User, :foreign_key => :approved_by_id
  belongs_to :voided_by,   :class_name => User, :foreign_key => :voided_by_id

  accepts_nested_attributes_for :purchase_order_lines
  attr_accessible :purchase_order_lines_attributes

  def self.branch_pending_purchase_orders(buyer_ids, branch_id)
    purchase_orders = buyer_ids.present? ? where(assigned_to_user_id: buyer_ids, branch_id: branch_id) : where(branch_id: branch_id)
    purchase_orders
  end

  def self.matching_purchase_order(status, category_id, supplier_id)     
    purchase_order = where("purchase_orders.status = ?", status)
    purchase_order = purchase_order.where("purchase_orders.product_category_id = ?", category_id)
    purchase_order = purchase_order.where("purchase_orders.supplier_id = ?", supplier_id)
    purchase_order
    # where("purchase_orders.product_category_id = ? AND purchase_orders.status = ? AND purchase_orders.supplier_id = ?", category_id, status, supplier_id)      
    # where(product_category_id: category_id, status: status, supplier_id: supplier_id)
  end

  def self.matching_purchase_order_via_category
    where("purchase_orders.product_category_id = ? AND purchase_order_lines.product_id = ?")
  end
end

app/controllers/api/v1/purchase_orders_controller.rb
module API
  module V1
    class PurchaseOrdersController < ApplicationController
      before_filter :authenticate
      respond_to :xml

      def authenticate
        authenticate_token || render_unauthorized
      end

      def authenticate_token
        authenticate_with_http_token do |token, options|
          @account_id = APIKey.find_by_access_token(token).account_id rescue nil
          @account_id.nil? ? false : true
        end
      end

      def render_unauthorized
        render xml: 'Bad credentials', status: 401
      end

      def index
        begin
          purchase_orders = paginate PurchaseOrder.where(account_id: @account_id, barter_receive_date: nil), per_page: 50

          purchase_orders = paginate purchase_orders.where(supplier_id: Supplier.find_by_code(params[:supplierCode].to_s).id), per_page: 50 if params[:supplierCode].present? 

          purchase_orders = paginate purchase_orders.where(branch_id: Branch.find_by_code(params[:branchCode].to_s).id), per_page: 50 if params[:branchCode].present? 

          po_array = []
          purchase_orders.each do |purchase_order|
            po_array << {
              poNumber: purchase_order.reference,
              branchCode: Branch.find(purchase_order.branch_id).code,
              buyerName: User.find(purchase_order.assigned_to_user_id).last_name,
              date: purchase_order.created_at.to_s,
              supplierCode: Supplier.find(purchase_order.supplier_id).code
            }
          end

          purchase_orders_hash = {poListSummary: {total: purchase_orders.count}, po: po_array }

          if purchase_orders.present?
            render xml: purchase_orders_hash.to_xml(:root => 'poRequest'), status: 200
          else
            head 204
          end
        rescue Exception
          head 500
        end
      end

      def show
        begin
          purchase_order = PurchaseOrder.where(account_id: @account_id, reference: params[:id]).first
          purchase_order_lines = paginate PurchaseOrderLine.where(purchase_order_id: purchase_order.reference), per_page: 50
          line_items_array = []

          po_summary_hash = {
            poNumber: purchase_order.reference,
            deliverTo: Branch.find(purchase_order.branch_id).name,
            branchCode: Branch.find(purchase_order.branch_id).code,
            supplierCode: Supplier.find(purchase_order.supplier_id).code,
            poDate: purchase_order.created_at,
            cancellationDate: purchase_order.cancellation_date,
            targetDate: purchase_order.due_date,
            remark: purchase_order.remarks,
            poLinesCount: purchase_order_lines.count,
            grossAmount: purchase_order.total_po_cost,
            totalItemDiscount: purchase_order.total_item_discount,
            overallDiscountText: purchase_order.overall_discount,
            netAmount: purchase_order.grand_total
          }

          purchase_order_lines.each_with_index do |purchase_order_line, idx|
            line_items_array << {
              lineNumber: (idx + 1),
              sku: Product.find(purchase_order_line.product_id).sku,
              purchaseQuantity: purchase_order_line.quantity_to_purchase,
              quantityPerUnit: purchase_order_line.quantity_per_unit,
              unitToPurchase: purchase_order_line.units_to_purchase,
              purchasePrice: purchase_order_line.purchase_price,
              itemDiscountText: purchase_order_line.discount_text,
              subTotal: purchase_order_line.subtotal
            }
          end

          purchase_order_detailed_hash = {poSummary: po_summary_hash, lineItems: {lineItem: line_items_array} }

          if params[:id].nil?
            head 422
          elsif purchase_order.present?
            render xml: purchase_order_detailed_hash.to_xml(:root => 'po'), status: 200
          else
            head 500
          end
        rescue Exception
          head 500
        end
      end

      def received
        begin
          xml_string = params[:data]
          data_hash = Hash.from_xml(xml_string)
          purchase_order_array = []
          data_hash['poList']['po'].each do |po|
            purchase_order = PurchaseOrder.find_by_reference(po['poNumber'].to_i)
            purchase_order.barter_receive_date = DateTime.now
            purchase_order_array << purchase_order
          end

          processing_po = purchase_order_array.paginate(page: 1, per_page: 50000)
          processing_po.total_entries.times do |i|
            PurchaseOrder.import(purchase_order_array.paginate(page: (i + 1), per_page: 50000), { validate: false, on_duplicate_key_update: [:barter_receive_date] })
          end

          render xml: 'Success', status: 200 
        rescue Exception
          head 500
        end
      end
    end
  end
end

app/controllers/api/v2/purchase_orders_controller.rb
module API
  module V2
    class PurchaseOrdersController < ApplicationController
      before_filter :authenticate
      respond_to :xml

      def authenticate
        authenticate_token || render_unauthorized
      end

      def authenticate_token
        authenticate_or_request_with_http_basic do |username, password|
          @account_id = APIKey.find_by_access_token(username).account_id rescue nil
          @account_id.nil? ? false : true
        end
      end

      def render_unauthorized
        render xml: 'Bad credentials', status: 401
      end

      def index
        begin
          purchase_orders = paginate PurchaseOrder.where(account_id: @account_id).where("status='V' OR status='A'"), per_page: 10

          purchase_orders = paginate purchase_orders.where('updated_at < ? ', params[:before].to_date), per_page: 10 if params[:before].present?

          purchase_orders = paginate purchase_orders.where('updated_at > ? ', params[:after].to_date.end_of_day), per_page: 10 if params[:after].present?

          purchase_orders = paginate purchase_orders.where('updated_at >= ? ', params[:from].to_date), per_page: 10 if params[:from].present?

          purchase_orders = paginate purchase_orders.where('updated_at <= ? ', params[:to].to_date.end_of_day), per_page: 10 if params[:to].present?

          po_array = []
          purchase_orders.each do |purchase_order|

            po_lines = purchase_order.purchase_order_lines#(:order => "id desc")
            po_lines_array = []
            po_lines.each do |po_line|
              #product_units = po_line.product.product_units
              #ordering_unit = product_units.where(ordering_unit: '1').first if product_units.present?
              #unit = ordering_unit.nil? ? po_line.product : ordering_unit
              
              # if po_line.quantity_per_unit == po_line.product.unit_content_quantity
              #   unit = po_line.product
              # else
              #   po_line.product.product_units.each do |x|
              #     if x.quantity_per_unit == po_line.quantity_per_unit 
              #       unit = x
              #     end
              #   end
              # end

              if po_line.product.base_unit_name == po_line.ordering_unit
                unit = po_line.product
              else
                po_line.product.product_units.each do |x|
                   if x.base_unit_name == po_line.ordering_unit
                    unit = x
                  end
                end
              end 

              po_lines_array << {
                  barcode: po_line.product.barcode,
                  quantity_to_purchase: po_line.quantity_to_purchase,
                  quantity_per_unit: po_line.quantity_per_unit,
                  units_to_purchase: po_line.units_to_purchase,
                  unit_name: unit.base_unit_name,
                  unit_code: unit.sku,
                  #effective_cost: po_line.subtotal / po_line.quantity_to_purchase.to_i,
                  purchase_price: po_line.purchase_price,
                  product_code: po_line.product.sku,
                  item_discount_text: po_line.discount_text,
                  subtotal: po_line.subtotal
              }
            end

            po_array << {
                purchase_order_number: purchase_order.reference,
                branch_code: Branch.find(purchase_order.branch_id).code,
                supplier_code: Supplier.find(purchase_order.supplier_id).code,
                cancellation_date: purchase_order.cancellation_date,
                target_date: purchase_order.created_at + 7.days,
                purchase_order_date: purchase_order.created_at,
                last_updated_at: purchase_order.updated_at,
                remarks: purchase_order.remarks,
                status: purchase_order.status,
                overall_discount_text: purchase_order.overall_discount,
                gross_amount: purchase_order.total_po_cost,
                total_item_discount: purchase_order.total_item_discount,
                net_amount: purchase_order.grand_total,
                purchase_order_lines: po_lines_array
            }
          end

          if purchase_orders.present?
            render xml: po_array.to_xml(root: 'purchase_orders', dasherize: false), status: 200
          else
            head 204
          end
        rescue Exception
          head 500
        end
      end
    end
  end
end

app/views/purchase_orders/_modal_order_to_supplier.html.haml
.modal.fade#order-to-supplier-modal{role: :dialog, 'aria-hidden'=>'true'}
	.modal-dialog.modal-sm
		.modal-content
			.modal-header
				%button.close{type: :button, 'data-dismiss' => 'modal'}
				%h4 Choose Supplier
			
			.modal-body
				%select.form-control#order-to-supplier-supp-id
				
			.modal-footer
				%button.btn.btn-default{type: :button, 'data-dismiss'=>'modal'} Close
				%button.btn.btn-primary#confirm-transfer-button{type: :button, 'data-dismiss'=>'modal'} Confirm

.modal.fade#choose-purchase-order-modal{role: :dialog, 'aria-hidden'=>true}
	.modal-dialog.modal-sm
		.modal-content
			.modal-header
				%button.close{type: :button, 'data-dismiss'=>'modal'}
				%h4 Choose PO Destination

			.modal-body
				%select.form-control#purchase-order-select

			.modal-footer
				%button.btn.btn-default{type: :button, 'data-dismiss'=>'modal'} Close
				%button.btn.btn-primary#confirm-order-select{type: :button, 'data-dismiss'=>'modal'} Select

app/views/purchase_orders/index.html.haml
%table#po.table.table-global{"data-source" => purchase_orders_url(format: "json")}
  %thead
    %tr
      %th No
      %th Ref #
      %th Supplier
      %th Generated At
      %th Category
      %th Action
  %tbody
    - no = 0
    - @purchase_orders.each do |po|
      %tr
        %td
          = no += 1
        %td= po.reference
        %td= link_to po.supplier.name, purchase_order_lines_purchase_order_path(po.id)
        %td= po.created_at.strftime('%m-%d-%Y %r')
        %td= po.product_category.name
        %td
          %span.po-btn3.btn.btn-info.btn-xs{'data-supplier-id' => po.supplier.id, 'data-po-id' => po.id}
            Copy PO


.modal.fade#copy-po{'aria-hidden'=>'true', 'role' => 'dialog'}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{'data-dismiss'=>'modal'}
          %span
            &times;
        %h3 Copy PO
      .modal-body
        #load-branches
      .modal-footer
        %span#copy-btn.btn.btn-primary{'data-dismiss'=>'modal'} Done
        %button.btn.btn-default{'data-dismiss'=>'modal'} Close


:javascript
  var supplierId = '', poId = '';

  $(".po-btn3").click(function() {
    supplierId = $(this).attr('data-supplier-id');
    poId = $(this).attr('data-po-id');
    $("#load-branches").load("#{get_branches_of_supplier_purchase_orders_path}?id=" + supplierId, function(data){
      $('#copy-po').modal('show');
    });
  });

  $("#copy-btn").click(function(){
    //gets branch id of selected branch
    var branch_id = $('#selected-branch').val();

    var params = { "supplier_id": supplierId, "purchase_order_id": poId, "branch_id": branch_id }
    $.post("#{copy_po_purchase_orders_path(params[:purchase_order_id])}", params)
     .done(function( data ) {
       if ( data == 'success' ) {
         document.location.href = '';
       } else {
         alert('Failed! Try again!');
       }
     });
  });

  $('#po').dataTable({
     sPaginationType: "full_numbers",
     bProcessing: true,
     bServerSide: true,
     sAjaxSource: $('#po').data('source')
  });

app/views/purchase_orders/purchase_order_lines.html.haml
= content_for :header do
  = stylesheet_link_tag 'po-lines'

.hide#review{'data-review-po' => @review_po.to_s , 'data-status' => @purchase_order.status, 'data-attr-id' => @purchase_order.id, 'po-lines' => @purchase_order.purchase_order_lines.count}
%br
.col-xs-12.col-lg-4.padding-0
  %table.table-unbordered
    %tr
      %th Reference #
      %td= @purchase_order.reference
    %tr
      %th Deliver To
      %td#branch-name= @purchase_order.branch.name
    %tr
      %th Supplier
      %td#supplier-name= @purchase_order.supplier.name
    %tr
      %th Status
      %td= @purchase_order.status.gsub(/[PCVA]/, 'P' => 'Pending', 'C' => 'Confirmed', 'V' => 'Voided', 'A' => 'Approved')
    %tr
      %th Category
      %td= @purchase_order.product_category.name
.col-xs-12.col-lg-4.padding-0
  %table.table-unbordered
    %tr
      %th PO Date:
      %td#po-date= @purchase_order.created_at.strftime("%F")
    %tr
      %th Cancellation Date:
      %td 
        - if @review_po == false || @purchase_order.status == 'A' || @purchase_order.status == 'V'
          %input.form-control#cancellation_date{type: :date, value: @purchase_order.cancellation_date.strftime("%F"), :disabled => :disabled}
        - else
          %input.form-control#cancellation_date{type: :date, value: @purchase_order.cancellation_date.strftime("%F")}   
    %tr
      %th Target Date:
      %td
        - if @review_po == false || @purchase_order.status == 'A' || @purchase_order.status == 'V'
          %input.form-control#target_date{type: :date, value: @purchase_order.due_date.strftime("%F"), :disabled => :disabled}
        - else
          %input.form-control#target_date{type: :date, value: @purchase_order.due_date.strftime("%F")}
       
    %tr
      %th Remark:
      %td
        %label.truncate#rem 
          = @purchase_order.remarks.blank? ? "--" : @purchase_order.remarks
        - if @review_po == true || @purchase_order.status == 'P' || @purchase_order.status == 'C'
          %span.btn.btn-xs.btn-success{'data-toggle'=>'modal', 'data-target'=>'#remarks-modal'} edit remarks
    %tr
      %th Terms:
      %td
        %input.form-control#supplier-terms{type: :text, value: @po_terms}
      
.col-xs-12.col-lg-4.padding-0
  %table.table-unbordered
    %tr
      %th Gross Total Cost:
      %td
        %span.label-default.label#gross-total-cost{'data-id'=>params[:id]}
          = number_to_currency(@total_po_cost.to_f, unit: "P ")
    %tr
      %th Total Item Discount:
      %td
        %span.label.label-default#total-item-discount
          = number_to_currency(@total_item_discount, unit: "P ")
    %tr
      %th Grand Total:
      %td
        %span.label.label-default#grand-total
          = number_to_currency(@gross_amount, unit: "P ")
    %tr
      %th Overall Discount
      %td
        - if @review_po == false || @purchase_order.status == 'A' || @purchase_order.status == 'V'          
          %input#od{type: :text, value: @overall_discount, :disabled => :disabled}            
        - else
          %input#od.form-control{type: :text, value: @overall_discount}    
    %tr
      %th Support Discount
      %td        
        %input.form-control#supplier-support-discount{type: :text, value: @po_support_ds}
          
    %tr
      %th Net Amount:
      %td
        %span.label.label-default#net-amount
          = number_to_currency(@grand_total, unit: "P ")

%br 
.div.padding-30 
  - if @purchase_order.status == 'P'
    .col-xs-12.padding-0
      - if @review_po == true
        %span.btn.btn-info.po-operation#savePo{'data-status' => @purchase_order.status} Save        
        %span.btn.btn-warning.po-operation#confirmPo Confirm        
        %span.glyphicon.glyphicon-plus.btn.btn-success.pull-right#add-po-line
  - elsif @purchase_order.status == 'C'
    .col-xs-12.padding-0
      - if @approve_void_po        
        %span.btn.btn-primary.po-operation#approvePo Approve
        = link_to 'Void', po_line_commit_purchase_order_path(id: params[:id], status: 'V'), class: 'btn btn-danger', method: :post, id: 'voidPo'
      - if @review_po == true
        %span.btn.btn-info.po-operation#savePo{'data-status' => @purchase_order.status} Save        
        %span.glyphicon.glyphicon-plus.btn.btn-success.pull-right#add-po-line      


.col-xs-12.padding-0
  - if @purchase_order.status == 'Pending' || @purchase_order.status == 'Confirmed'
    %table.table.table-global.po-table#po-lines{"data-source" => purchase_order_lines_purchase_order_url(format: "json")}
      %thead
        %tr
          %th No
          %th Product
          %th Sales and Inventory
          %th Order Details
          %th Cost
          %th{width: '100px'} Action
      %tbody
  - else
    %table.table.table-global.po-table#po-lines{"data-source" => purchase_order_lines_purchase_order_url(format: "json")}
      %thead
        %tr
          %th No
          %th Product
          %th Units to Purchase
          %th Purchase Price
          %th Discount
          %th Subtotal
      %tbody

.modal.fade#remarks-modal{'aria-hidden'=>'true'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>'modal'}
          %span{'aria-hidden'=>'true'} &times;
        %h4 Purchase Order Remarks
      .modal-body
        %textarea#remarks-textarea.form-control{rows: 15}= @purchase_order.remarks
      .modal-footer
        %button.btn.btn-default#dismiss{'data-dismiss'=>'modal'} Close
        %button.btn.btn-primary#save-remarks Save changes

.modal.fade#graphs-modal{'aria-hidden'=>'true'}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>'modal'}
          %span{'aria-hidden'=>'true'} &times;
        %h4#modal-product-name
      .modal-body{style: 'min-height: 510px;'}

        .col-xs-4
          .panel.panel-primary
            .panel-heading Details
            .panel-body.graphs
              %li
                %label Supplier:
                %span#modal-branch-name
              %li
                %label Branch:
                %span#modal-supplier-name              
              %li
                %label Last Received Date:
                %span#modal-last-received-date
              %li
                %label Last Received Qty:
                %span#modal-last-received-qty

        .col-xs-4
          .panel.panel-primary
            .panel-heading#modal-po-date
            .panel-body#modal-supplier-name.graphs
              %li
                %label Average Daily Sales:
                %span#modal-average-daily-sales
              %li
                %label On-hand Quantity:
                %span#modal-on-hand-quantity
              %li
                %label Suggested Quantity:
                %span#modal-suggested-quantity
              %li
                %label SRP:
                %span#modal-srp
        .col-xs-4
          .panel.panel-primary
            .panel-heading Duration
            .panel-body.graphs
              %li
                %select#duration.form-control
                  %option{value: 7} 
                  %option{value: 30} Last 30 Days
                  %option{value: 60} Last 60 Days
                  %option{value: 90} Last 90 Days
                  %option{value: 0} Custom
              %li{style: 'padding-bottom: 5px;'}
              %li.date-cont                
                .col-xs-12.padding-0
                  .input-group.input-group-sm
                    %span.input-group-addon
                      from
                    %input#from.form-control{onblur: 'dateFromTo()', type: :date, value: Date.today.strftime('%F'), min: (Date.today - 3.years).strftime('%F')}              
              %li.date-cont                
                .col-xs-12.padding-0
                  .input-group.input-group-sm{ style: 'padding-top: 5px;' }
                    %span.input-group-addon{style: "width: 47px;"}
                      to
                    %input#to.form-control{onblur: 'dateFromTo()', type: :date, style: "width: 179px;", value: Date.today.strftime('%F'), min: (Date.today - 3.years).strftime('%F')}


        .col-xs-12
          %ul.nav.nav-tabs{role: :tablist}            
            %li
              %a#sinv-btn{href: '#sales-inv', 'data-toggle' => 'tab'} Sales & Inventory
            %li
              %a#isr-btn{href: '#inventory-sales-ratio', 'data-toggle' => 'tab'} Inventory-Sales Ratio
            %li
              %a#hd-btn{href: '#historical-data', 'data-toggle' => 'tab'} Historical Data

        .col-xs-12
          .tab-content
            .fade.tab-pane#sales-inv
              #sales-inventory
              .legend-sales
              %label.legend-lbl Sales
              .legend-inventory
              %label.legend-lbl Inventory
            .fade.tab-pane#inventory-sales-ratio
            .fade.tab-pane#historical-data
      .modal-footer
        %span.btn.btn-default{'data-dismiss'=>'modal'} Close

.div#refresh
  .modal.fade#add-line-modal{role: :dialog, 'aria-hidden'=>'true'}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{type: :button, 'data-dismiss'=>'modal'}
            %span{'aria-hidden'=>'true'} &times;
          %h4 Choose Product
        .modal-body
          #get_prod_to_add

= render partial: "modal_order_to_supplier"

- content_for :footer do
  = javascript_include_tag 'po-lines-datatable'
  = javascript_include_tag 'purchase_order_lines/purchase_order_lines_actions'
  = javascript_include_tag 'Chart.min'

app/views/purchase_orders/show.html.haml
.hide#review{'po-count' => @purchase_orders.count}
%table#purchase_orders.table.table-global{"data-source" => purchase_order_url(format: "json")}
  %thead
    %tr
      %th No
      %th Ref #
      %th Supplier
      %th Branch
      %th Category
      %th Generated At
      %th Action
  %tbody

%form#copy-po-form
  .modal.fade#copy-po-modal{'aria-hidden' => 'true'}
    .modal-dialog.modal-sm
      .modal-content
        .modal-header
          %button.close{type: :button, 'data-dismiss' => 'modal'}
            %span{'aria-hidden' => 'true'} &times;
          %h4.modal-title Choose Branch
        .modal-body
          #load-branches
        .modal-footer
          %button.btn.btn-default{type: :button, 'data-dismiss' => 'modal'} Close
          %span.btn.btn-primary#trigger-copy-po Duplicate

:javascript
  var po_count = $("#review").attr('po-count');

  if (parseInt(po_count) > 10)
    paginate = true;
  else
    paginate = false;

  alert(po_count);
  
- content_for :footer do
  = javascript_include_tag 'po-list'