config/routes.rb
IrippleCloudbuy::Application.routes.draw do

  root to: 'sessions#new'

  resources :suppliers do
    member do
      get :activate
      get :products
      get :purchase_orders
      get :activate_product
      post :assigner
      post :unassigner
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned' 
      get :purchase_orders
    end
    collection do
      get :get_product_categories      
    end
  end

  resources :branches do
    member do
      post :assigner
      post :unassigner
      post :getSched
      post :assign_default_supplier
      get  :get_products_duplicate_assign  
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned'
    end

    collection do
      get   :get_branches_of_supplier
    end
  end

  resources :purchase_orders, path: '/purchase-orders' do
    member do
      post   :add_po_line
      post   :del_po_line
      get    :get_prod_to_add 
      get   :purchase_order_lines, path: '/purchase-order-lines'
      post  :po_line_commit, path: '/po-line-commit'
      post  :add_remarks, path: '/add-remarks'
    end

    collection do
      post  :update_line_items, path: '/update-line-items'
      post  :trigger_manual_po, path: '/manual-po'
      post  :copy_po
    end
  end

  resources :purchase_order_lines, path: '/purchase-order-lines' do    
    collection do
      get  :order_to_suppliers, path: '/order-to-suppliers'
      post :transfer_to_supplier, path: '/transfer-to-supplier'
      post :commit_transfer_to_supplier, path: '/commit-transfer-to-supplier'
    end
  end

  resources :dashboards do    
    collection do
      get :supplier_index
      post :upload
    end
  end

  resources :users do
    member do
      get   :activate
      get   :assigned_suppliers
      get   :unassigned_suppliers
      get   :recover_password, path: '/recover-password'
      post  :assigner
      post  :unassigner
    end
    collection do
      get   :view_api_key, path: '/view-api-key'
      get   :forget_password, path: '/forget-password'
      get   :change_password, path: '/change-password'
      put   :change_password, path: '/change-password'
      post  :send_password
      post  :reset_password
    end
  end

  resources :sessions do
    collection do
      post :locate_subdomain
    end
  end

  namespace :admin do
    get '' => 'sessions#new'
    resources :sessions
    resources :dashboards
    resources :accounts do
      member {
        get :run_indexing
      }
    end
    resources :users    
  end

  resources :transactions do
    collection {
      get :historical_data, path: '/historical-data'
      get :sales_and_inventory_data, path: '/sales-and-inventory'
      get :inventory_sales_ratio, path: '/inventory-sales-ratio'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :purchase_orders, only: [:index,:show, :received], path: '/purchase_orders' do
        collection do
          post 'received'
        end
      end
    end
    namespace :v2 do
      resources :purchase_orders, only: [:index], path: '/purchase_orders'
    end
  end

  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :user_access, :parent_id,
                  :last_name, :role, :status, :supervisor_id, :account_id, :password_hash, :password_salt, :reset_password_token

  attr_accessor :password

  before_save   :encrypt_password

  validates_confirmation_of :password  
  validates_presence_of     :email, :first_name, :password
  validates_uniqueness_of   :email
  validates_length_of       :password, minimum: 8


  has_one    :po_number
  has_many   :buyer_suppliers
  has_many   :roles
  has_many   :suppliers,  through: :buyer_suppliers, dependent: :destroy
  has_many   :products, through:  :suppliers
  has_many   :buyers,     class_name: User, foreign_key: :supervisor_id
  has_many   :sub_users,  class_name: User, foreign_key: :parent_id
  has_many   :branches,   through: :suppliers
  belongs_to :supervisor, class_name: User, foreign_key: :supervisor_id
  belongs_to :admin,      class_name: User, foreign_key: :id
  belongs_to :account


  has_many  :ownerships
  has_many  :product_categories, through: :ownerships  
  has_many  :purchase_orders, class_name: PurchaseOrder, foreign_key: :assigned_to_user_id

  belongs_to :user

  accepts_nested_attributes_for :roles

  attr_accessible :roles_attributes

  def self.active_supervisor_buyers(supervisor_id)
    where(supervisor_id: supervisor_id, status: 'A').map(&:id)
  end

  def self.search_keyword(keyword, tempArg)
    if keyword
      find(:all, limit: 10, conditions: [ 'suppliers.id NOT IN (?) AND suppliers.name LIKE ?', tempArg, "%#{keyword}%" ])
    else
      find(:all, limit: 10)
    end
  end

  def self.nodeleted(user)
    if user.role == 'supervisor'
      where('status <> ? and role <> ? and role <> ? and id <> ? and supervisor_id = ? and role <> ?' , 'D', 'cb_admin', 'owner', user.id, user.id, 'merchant admin')
    elsif  user.role == 'merchant admin'
      where('status <> ? and role <> ? and role <> ? and id <> ?' , 'D', 'cb_admin', 'owner', user.id)
    else
      where('status <> ? and role <> ? and id <> ?', 'D', 'cb_admin', user.id)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.cb_admins
    user = where(role: 'cb_admin')
  end

  def self.locate_subdomain(email)
    user = find_by_email(email, conditions: ['role <> ?', 'cb_admin'] ) rescue nil
    if user.nil?
      nil
    else
      user.account.subdomain
    end
  end

  def self.is_cb_admin?
    if self.role.to_s == 'cb_admin'
      true
    else
      false
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  layout 'admin'
  before_filter :check_session

  def index
    @users = User.cb_admins
  end

  def new
    @user = User.new
  end

  def create
    userAttributes = params[:user].merge(role: 'cb_admin')
    @user = User.new(userAttributes)
    if @user.save
      redirect_to admin_users_path, notice: 'Successfully created!'
    else
      render 'new'
    end
  end

  private

  def check_session
    if current_user.nil? || current_user.role != 'cb_admin'
      redirect_to new_admin_session_path, alert: 'Session expired. Please re login!'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  

  require "will_paginate/array"

  before_filter :check_session, except: [:forget_password, :send_password, :recover_password, :reset_password]
  before_filter :check_if_user_belongs_to_account, only: [ :assigned_suppliers, :unassigned_suppliers, :assigner, :unassigner, :edit,  :destroy, :update, :activate ]
  layout false, only: [:unassigned_suppliers, :assigned_suppliers]

  def index    
    respond_to do |format|
      format.html
      format.json { render json: UsersDatatable.new(view_context, @account , merchant_current_user) }
    end    
  end

  def view_api_key
    add_breadcrumb "API Key"
    @user = merchant_current_user    
    @api_key = @user.account.api_key.access_token    
  end

  def change_password
    @user = merchant_current_user
    if request.method.to_s == 'POST'
      if @user.update_attributes(params[:user])
        redirect_to change_password_users_path, notice: 'Account has been updated successfully!'
      else
        render 'change_password'
      end
    end
  end

  def update_password
    render json: params
  end

  def new
    add_breadcrumb "Add New User"
    @user  = User.new
    @user.roles.build
  end

  def assigned_suppliers
    @distributors = @checked_user.suppliers.where(status: 'A', is_principal: false)
    respond_to do |format|
      format.html
      format.json { render json: AssignedSuppliersDatatable.new(view_context, @distributors, "user", @user) }
    end
  end

  def unassigned_suppliers    
    respond_to do |format|
      format.html
      format.json { render json: PendingSuppliersDatatable.new(view_context, :user, @checked_user) }
    end
    
  end

  def assigner

    if @checked_user.role == 'buyer'
      supervisor = @account.users.find(@checked_user.supervisor_id)
      supervisor.buyer_suppliers.create(supplier_id: params[:supplier_id])
    end

    buyerSupplier = @checked_user.buyer_suppliers.new(supplier_id: params[:supplier_id])
    if buyerSupplier.save
      category_ids_arr = params[:category_ids].split(',')
      category_ids_arr.each do |i|
        @account.ownerships.create(product_category_id: i, supplier_id: params[:supplier_id], user_id: params[:id])
      end
      render text: 'success'
    else
      render text: 'failed'
    end

  end

  def unassigner

    if @checked_user.role == 'buyer'
      supervisor = @account.users.find(@checked_user.supervisor_id)
      supervisorSupplier = supervisor.buyer_suppliers.where(supplier_id: params[:supplier_id]).first
      supervisorSupplier.destroy
    end

    buyerSupplier = @checked_user.buyer_suppliers.where(supplier_id: params[:supplier_id]).first
    ownershipTable = @account.ownerships.where(supplier_id: params[:supplier_id], user_id: params[:id])
    
    if buyerSupplier.destroy && ownershipTable.destroy_all
      render text: 'success'
    else
      render text: 'failed'
    end
  end

  def create
    @user = merchant_current_user.sub_users.new(params[:user].merge(account_id: @account.id))
    if @user.save
      redirect_to users_path, notice: 'User has been added successfully!'
    else
      render 'new'
    end
  end

  def edit
    @supervisor = @account.users.where(role: :supervisor, status: 'A').where('id != ?', params[:id])
    @user = @account.users.find(params[:id])
    @user.roles.build
    add_breadcrumb "#{@user.first_name} #{@user.last_name}"
  end

  def update
    @user = @checked_user
    user_params = params[:user]
    role_params = user_params.delete('roles_attributes')
    user_params = user_params.except('roles_attributes') if user_params.nil? == false
    if user_params.present?
      result = @user.update_attributes(user_params)
    end
    if role_params.present?
      @user.roles.destroy_all
      role_params.each do |role|
        @user.roles.create(role)
      end
      result = true
    end
    if result
      redirect_to users_path
      flash[:notice] = 'User successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @user = @checked_user
    @user.status = 'D'
    @user.save
    redirect_to users_path
    flash[:notice] = 'User successfully deleted.'
  end

  def activate
    @user = @checked_user
    if @user.status == 'A'
      @user.update_attribute('status', 'I')
    else
      @user.update_attribute('status', 'A')
    end
    redirect_to users_path
    flash[:notice] = 'User status successfully updated.'
  end

  def forget_password
  end

  def send_password
    user = User.find_by_email(params[:email])
    if user
      reset_password_token = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless User.exists?(reset_password_token: random_token)
      end
      if user.update_attributes(reset_password_token: reset_password_token)
        MerchantMailer.reset_password(params[:email], reset_password_token, user.account.subdomain).deliver
        render text: 'sent'
      else
        render text: 'failed'
      end
    else
      render text: 'unknown'
    end
  end

  def reset_password
    user = User.find_by_reset_password_token(params[:id])
    if user
      user.update_attributes(password: params[:password_reset])
      render text: 'success'
    else
      render text: 'failed'
    end
  end

  private

  def check_if_user_belongs_to_account
    @checked_user = @account.users.find(params[:id])
    if @checked_user.nil?
      redirect_to users_path, alert: 'Unable to find user. Try again!'
      return
    end
  end

  def check_session
    if !merchant_current_user.nil?
      @account = merchant_current_user.account
      @user = merchant_current_user
      if @account.subdomain.to_s != request.subdomain.to_s
        session[:merchant_current_user] = nil
        redirect_to new_session_path, alert: 'Session expired. Please re login'
      end
      add_breadcrumb "Dashboard", :dashboards_path
      add_breadcrumb "Users",     :users_path
    else
      redirect_to new_session_path, notice: 'Session expired! Please re login!'
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :role, :supervisor_id,  :roles_attributes => [:name])
  end

end

app/views/users/assigned_suppliers.html.haml
= page_entries_info @result
%table.table
  %tr
    %th No
    %th Supplier Name
    %th Action
  - no = 0
  - @result.each do |supplier|
    %tr
      %td= no += 1
      %td= supplier.name
      %td
        %span.btn.btn-xs.btn-primary.supplier-btn2{'data-supplier-id' => supplier.id } Unassign
= will_paginate @result, class: 'assigned-paginate'

:javascript
  $(".supplier-btn2").click(function(){
    var supplierId = $(this).attr('data-supplier-id');
    var params = { "supplier_id": supplierId }
    $.post("#{unassigner_user_path(params[:id])}", params)
     .done(function( data ) {
        if ( data == 'success' ) {
          reload();
        } else {
          swal("Oh Snap!", "Something went wrong. Please try again!", "error");
        }
     });
  });

  $(function(){
    $(".assigned-paginate a").click(function(event){
      event.preventDefault();
      var link = $(this).attr('href');
      $("#assigned_suppliers_container").load(link, function(){});
    });
  });

app/views/users/change_password.html.haml
%br
.col-lg12
  %font{style: "font-size:14px"}
    %ol.breadcrumb
      %li 
        = link_to('Dashboard', dashboards_path)
      %li
        = link_to 'Users', users_path
      %li.active
        = "#{@user.first_name}"
        
.col-xs-4
  %h2 Edit Basic Information
  - if @user.errors.any?
    - @user.errors.each do |k, v|
      .alert.alert-danger.alert-dismissable
        %button.close{ 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }
          = '&times;'.html_safe
        %strong= k
        = v
  = form_for @user, url: url_for(action: :change_password), method: :put do |u|
    .form-group
      %label First Name
      = u.text_field :first_name, class: 'form-control'
    .form-group
      %label Last Name
      = u.text_field :last_name, class: 'form-control'
    .form-group
      %label Email
      = u.email_field :email, class: 'form-control'
    .form-group
      %label Password
      = u.password_field :password, class: 'form-control'
    .form-group
      %label Confirm Password
      = u.password_field :password_confirmation, class: 'form-control'
    .form-group
      = u.submit 'Submit', class: 'btn btn-primary btn-sm'
      = link_to 'Cancel', users_path, class: 'btn btn-danger btn-sm'

app/views/users/edit.html.haml
:javascript
  var user_id_params;
  $(document).ready(function(){
      user_id_params = $("#review").attr('data-attr-par');
  });

:css 
  div.dataTables_processing {
    font-weight: bold;
    color: #428bca;
    border: 0px;
  }
.hide#review{'data-attr-par' => params[:id]}  
%br
%ul.nav.nav-tabs{role: :tablist}
  %li.active#udt
    %a{href: '#user_details_tab', role: :tab, 'data-toggle'=>'tab', id: 'udt_select'} User Details
  - if merchant_current_user.role == 'owner'
    %li#st
      %a{href: '#suppliers_tab', role: :tab, 'data-toggle'=>'tab', id: 'st_select'} Suppliers


.tab-content

  / DISTRIBUTORS
  .tab-pane#suppliers_tab
    .col-lg-6
      %h2 Suggested Suppliers
      %table#pending-distributors.table.table-global{"data-source" => unassigned_suppliers_user_url(format: "json")}
        %thead
          %tr
            %th No
            %th Supplier Name
            %th Action
        %tbody
    .col-lg-6
      %h2 Assigned Suppliers
      %table#assigned-distributors.table.table-global{"data-source" => assigned_suppliers_user_url(format: "json")}
        %thead
          %tr
            %th No
            %th Supplier Name
            %th Action
        %tbody
  


  / USER DETAILS   
  .tab-pane.active#user_details_tab
    %br
    .col-md-6.col-xs-12.col-lg-6
      = form_for @user, url: url_for(action: :update) do |u|
        .form-group
          %label First Name
          = u.text_field :first_name, class: 'form-control'
        .form-group
          %label Last Name
          = u.text_field :last_name, class: 'form-control'
        .form-group
          %label Email
          = u.email_field :email, class: 'form-control'
        .form-group
          %label Password
          = u.password_field :password, class: 'form-control'
        .form-group
          - if merchant_current_user.role == 'owner'
            - options = ['supervisor', 'buyer']
          - else
            - options = %w(supervisor buyer)
        - if merchant_current_user.role == 'owner'
          .form-group#user-type
            %label User Types
            = u.select :role, options.map {|value| [value.titleize, value]}, {},  {class: 'form-control', id: :user_types}
          %br
          .form-group#supervisor{style: 'display: none;'}
            %label Supervisor
            = u.select :supervisor_id, @supervisor.map {|value| [value.first_name + " " + value.last_name, value.id]}, {},  {class: 'form-control', id: :supervisor}
          .form-group{class: 'display: #{"none" if}'}
          %label User Roles
          - role = @user.roles.map(&:name)
          = u.fields_for :roles_attributes do |r|
            %div#rpo_b
              %input#rpo{value: :rpo, name: 'user[roles_attributes][][name]', type: :checkbox, checked: role.include?('rpo') ? true : false}
              %label{for: :rpo} Confirm POs
            %div#apo_b
              %input#apo{value: :apo, name: 'user[roles_attributes][][name]', type: :checkbox, checked: role.include?('apo') ? true : false}
              %label{for: :apo} Approve and Void POs
            %div
              %input#cpo{value: :cpo, name: 'user[roles_attributes][][name]', type: :checkbox, checked: role.include?('cpo') ? true : false}
              %label{for: :cpo} Duplicate POs
            %div
              %input#cpo{value: :epo, name: 'user[roles_attributes][][name]', type: :checkbox , checked: role.include?('epo') ? true : false}
              %label{for: :epo} Edit Purchase Price in PO Line
            %div
              %input#ssu{value: :ssu, name: 'user[roles_attributes][][name]', type: :checkbox, checked: role.include?('ssu') ? true : false}
              %label{for: :ssu} Suspend Suppliers
            %div
              %input#spr{value: :spr, name: 'user[roles_attributes][][name]', type: :checkbox, checked: role.include?('spr') ? true : false}
              %label{for: :spr} Suspend Products
        %br
        .form-group
          = u.submit 'Submit', class: 'btn btn-primary btn-sm'
          = link_to 'Cancel', users_path, class: 'btn btn-danger btn-sm'


// Assign Suppliers
  


// Modal for supplier assignment
.modal.fade#assign-supplier{role: :dialog, 'aria-hidden'=>'true'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: :button, 'data-dismiss'=>'modal'}
          %span{'aria-hidden'=>'true'} &times;
        %h4 Assign Product Tags
      .modal-body
        #load-product-categories
      .modal-footer
        %button.btn.btn-default{type: :button, 'data-dismiss'=>'modal'} Close
        %button.btn.btn-primary#submit-changes{type: :button, 'data-dismiss'=>'modal'} Save Changes



:javascript

  $(document).ready(function() {
    $("#rpo").change(function() {
      var value = $("#user_types").val();
      if (value == 'buyer') {
        if($(this).is(":checked"))
          $("#apo").prop('disabled', true);
        else
        {
          $("#apo").prop('disabled', false);  
          $("#rpo").prop('disabled', true);  
        }
      }
    });

    $("#apo").change(function() {
      var value = $("#user_types").val();
      if (value == 'buyer') {
        if($(this).is(":checked")) 
          $("#rpo").prop('disabled', true);
        else
        {
          $("#rpo").prop('disabled', false);  
          $("#apo").prop('disabled', true);  
        }
      }
    });
  });
    

  $(document).ready(function() {
    var value = $("#user_types").val();
    if (value == 'buyer')
      $("#supervisor").css('display', 'block');
    else
      $("#supervisor").css('display', 'none');
  });

  $("#user_types").change(function(){
    var value = $(this).val();
    if (value == 'buyer') {
      $("#supervisor").css('display', 'block');

      $("#rpo").prop('checked', true);
      $("#apo").prop('checked', false);
      $("#cpo").prop('checked', true);
      $("#epo").prop('checked', true);
      $("#ssu").prop('checked', false);
      $("#spr").prop('checked', false);

      $("#apo").prop('disabled', true);
    }
    else {
      $("#supervisor").css('display', 'none');

      $("#apo").prop('disabled', false);

      $("#rpo").prop('checked', true);
      $("#apo").prop('checked', true);
      $("#cpo").prop('checked', true);
      $("#epo").prop('checked', true);
      $("#ssu").prop('checked', true);
      $("#spr").prop('checked', true);
    }
  });


  var table = $('#pending-distributors').DataTable({
    sPaginationType: "full_numbers",
    bProcessing: true,
    bServerSide: true,
    sAjaxSource: $('#pending-distributors').data('source'),
  });

  var table2 = $('#assigned-distributors').DataTable({
    sPaginationType: "full_numbers",
    bProcessing: true,
    bServerSide: true,
    sAjaxSource: $('#assigned-distributors').data('source'),
  });


  // Supplier Assignment

  $("#submit-changes").click(function(){
    var values = $('#category-tags').val();
    var params = { "supplier_id": supplierId, "category_ids": values }

    var btn = $("#assign-action-" + global_supplier_id);

    btn.css("background-color", "#f0ad4e");
    btn.css("border-color", "#eea236");

    btn.button('loading');
    
    $.post("#{assigner_user_path(params[:id])}", params)
      .done(function(data){
        if ( data == 'success' ) {
          table.ajax.reload();
          table2.ajax.reload();
        } else {
          swal("Oh Snap!", "Something went wrong. Please try again!", "error");
        }        
      }
    );    
  });

  $("#udt").click(function(){
    document.location.href = "#udt";
    table.ajax.reload();
    table2.ajax.reload();
  });

  $("#st").click(function(){
    document.location.href = "#st";
  });

  $(document).ready(function(){
    var hash = document.location.hash;
    $(hash.toString() + "_select").click();
  });

app/views/users/forget_password.html.haml
.col-xs-4
  %h2
    Enter your email address
  .form-group
    %input.form-control#email-field{type: :email}
  .form-group
    %button.btn.btn-primary.col-xs-12#reset-btn{ 'data-loading-text' => 'Sending....' }
      Send Reset Password

:javascript
  $("#reset-btn").click(function(){
    var btn = $(this);
    btn.button('loading');
    $.post("#{send_password_users_path}", { "email": $("#email-field").val() }, function(data){
      if (data == 'sent')
      {        
        swal("Oops...", "Please check your email address!", "error");
      } else if ( data == 'unknown' )
      {        
        swal("Oops...", "User is not yet registered!", "error");
      } else
      {        
        swal("Oh Snap!", "Sending failed. Please try again!", "error");
      }
      btn.button('reset');
    })
  });

app/views/users/index.html.haml
.col-xs-12.padding-0
  .col-lg-6.padding-0
    %h2 List of Users
  .col-lg-6.padding-0
    %h2.text-right
      = link_to 'Add Another User', new_user_path, class: 'btn btn-success'
%table#users.table-global.table{"data-source" => users_url(format: "json")}
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Email Address
      %th Date Registered
      %th Role
      %th Action
  %tbody



:javascript
  $(function(){
    setTimeout(function() {
    $(".alert").fadeOut('slow');}, 3000
    );
  });

  var table = $('#users').DataTable({
    sPaginationType: "full_numbers",
    bProcessing: true,
    bServerSide: true,
    sAjaxSource: $('#users').data('source'),
    fnDrawCallback: function(){
        if($("#suppliers").find("tr:not(.ui-widget-header)").length<=5){
            $('#users_paginate').css("display", "none");
        } else {
            $('#users_paginate').css("display", "block");
        }
    }
  });
  

app/views/users/recover_password.html.haml
%br
.col-lg12
  %font{style: "font-size:14px"}
    %ol.breadcrumb
      %li 
        = link_to('Dashboard', dashboards_path)
      %li
        = link_to 'Users', users_path
      %li.active
        = "#{@user.first_name}"
        
.col-xs-4
  %h2 Reset Password

  .form-group
    %label New Password
    %input.form-control#p1{type: :password, name: :password_reset}

  .form-group
    %label Confirm New Password
    %input.form-control#p2{type: :password, name: :password_reset2}

  .form-group
    %button.btn.btn-primary#reset-btn Reset

:javascript

  $("#reset-btn").click(function(){
    var p1 = $("#p1").val();
      var p2 = $("#p2").val();

      if ( p1 == p2 )
      {
        $.post("#{reset_password_users_path(id: params[:id])}", {"password_reset": p1}, function(data){
          if (data == 'success') {            
            swal("Hola!", "Password has been sent to your email address.", "success");
            document.location.href = '#{root_url}';
          } else {            
            swal("Oops...", "Something went wrong. Try again!", "error");
          }
        });
      } else
      {        
        swal("Oops...", "Password not matched. Try again!", "error");
      }
  });

app/views/users/unassigned_suppliers.html.haml
= page_entries_info @result
%table.table
  %tr
    %th No
    %th Supplier Name
    %th Action
  - no = 0
  - @result.each do |supplier|
    %tr
      %td= no += 1
      %td= supplier.name
      %td
        %span.btn.btn-xs.btn-primary.supplier-btn{'data-supplier-id' => supplier.id} Assign
= will_paginate @result, class: 'unassigned-paginate'

:javascript

  var supplierId = '';

  $(".supplier-btn").click(function() {
    supplierId = $(this).attr('data-supplier-id');
    $("#load-product-categories").load("#{get_product_categories_suppliers_path}?id=" + supplierId, function(data){
      $('#assign-supplier').modal('show');
    });
  });

  // For pagination

  $(".unassigned-paginate a").click(function(event){
    event.preventDefault();
    var link = $(this).attr('href');
    $("#unassigned_suppliers_container").load(link, function(){});
  });

app/views/users/view_api_key.html.haml
.col-xs-4
  %h2 API Key
  - if @user.errors.any?
    - @user.errors.each do |k, v|
      .alert.alert-danger.alert-dismissable
        %button.close{ 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }
          = '&times;'.html_safe
        %strong= k
        = v
  %ul.list-group
    %li.list-group-item
      = @api_key