config/routes.rb
IrippleCloudbuy::Application.routes.draw do

  root to: 'sessions#new'

  resources :suppliers do
    member do
      get :activate
      get :products
      get :purchase_orders
      get :activate_product
      post :assigner
      post :unassigner
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned' 
      get :purchase_orders
    end
    collection do
      get :get_product_categories      
    end
  end

  resources :branches do
    member do
      post :assigner
      post :unassigner
      post :getSched
      post :assign_default_supplier
      get  :get_products_duplicate_assign  
      get :search_unassigned, path: '/search-unassigned'
      get :search_assigned,   path: '/search-assigned'
    end

    collection do
      get   :get_branches_of_supplier
    end
  end

  resources :purchase_orders, path: '/purchase-orders' do
    member do
      post   :add_po_line
      post   :del_po_line
      get    :get_prod_to_add 
      get   :purchase_order_lines, path: '/purchase-order-lines'
      post  :po_line_commit, path: '/po-line-commit'
      post  :add_remarks, path: '/add-remarks'
    end

    collection do
      post  :update_line_items, path: '/update-line-items'
      post  :trigger_manual_po, path: '/manual-po'
      post  :copy_po
    end
  end

  resources :purchase_order_lines, path: '/purchase-order-lines' do    
    collection do
      get  :order_to_suppliers, path: '/order-to-suppliers'
      post :transfer_to_supplier, path: '/transfer-to-supplier'
      post :commit_transfer_to_supplier, path: '/commit-transfer-to-supplier'
    end
  end

  resources :dashboards do    
    collection do
      get :supplier_index
      post :upload
    end
  end

  resources :users do
    member do
      get   :activate
      get   :assigned_suppliers
      get   :unassigned_suppliers
      get   :recover_password, path: '/recover-password'
      post  :assigner
      post  :unassigner
    end
    collection do
      get   :view_api_key, path: '/view-api-key'
      get   :forget_password, path: '/forget-password'
      get   :change_password, path: '/change-password'
      put   :change_password, path: '/change-password'
      post  :send_password
      post  :reset_password
    end
  end

  resources :sessions do
    collection do
      post :locate_subdomain
    end
  end

  namespace :admin do
    get '' => 'sessions#new'
    resources :sessions
    resources :dashboards
    resources :accounts do
      member {
        get :run_indexing
      }
    end
    resources :users    
  end

  resources :transactions do
    collection {
      get :historical_data, path: '/historical-data'
      get :sales_and_inventory_data, path: '/sales-and-inventory'
      get :inventory_sales_ratio, path: '/inventory-sales-ratio'
    }
  end

  namespace :api do
    namespace :v1 do
      resources :purchase_orders, only: [:index,:show, :received], path: '/purchase_orders' do
        collection do
          post 'received'
        end
      end
    end
    namespace :v2 do
      resources :purchase_orders, only: [:index], path: '/purchase_orders'
    end
  end

  match 'active'  => 'sessions#active',  via: :get
  match 'timeout' => 'sessions#timeout', via: :get


end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title IrippleCloudbuy
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        %a.navbar-brand{href: "#"}
          %img{src: image_path('cloudbuylogo_xsm.png')}
        = link_to 'CloudBuy', root_path, class: 'navbar-brand'

        %button.navbar-toggle{"data-target" => ".navHeaderCollapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

        .collapse.navbar-collapse.navHeaderCollapse
          %ul.nav.navbar-nav
            - if current_user
              %li.verticalline-navbar
              %li
                = link_to 'Dashboard', admin_dashboards_path
              %li
                = link_to 'Merchants', admin_accounts_path
              %li
                = link_to 'Users', admin_users_path
          - if current_user
            %ul.nav.navbar-nav.navbar-right
              %li
              %li.dropdown
                %a.dropdown-toggle{href: '#', 'data-toggle'=>'dropdown'}
                  %span= current_user.first_name
                  %span.caret
                %ul.dropdown-menu
                  %li
                    %a
                      Change Password
                  %li
                    = link_to 'Log Out', admin_session_path('delete-cb-user'), method: :delete


    .view-spacer
    .container
      - flash.each do |name, msg|
        - if name.to_s == 'notice'
          .alert.alert-info.alert-dismissable
            %button.close{ 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }
              = '&times;'.html_safe
            %strong Well done!
            = msg
        - elsif name.to_s == 'alert'
          .alert.alert-danger.alert-dismissable
            %button.close{ 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }
              = '&times;'.html_safe
            %strong Oh snap!
            = msg
      = yield
    .view-spacer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Welcome to CloudBuy
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body#bdy
    .navbar.navbar-default.navbar-fixed-top
      .container
        %a.navbar-brand{href: "#"}
          %img{src: image_path('cloudbuylogo_xsm.png')}
        = link_to 'CloudBuy', root_path, class: 'navbar-brand'

        %button.navbar-toggle{'data-target'=>'.navbar-collapse', 'data-toggle'=>'collapse'}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if merchant_current_user
              %li= link_to 'Dashboard', dashboards_path
              %li= link_to 'Suppliers', suppliers_path
              - if merchant_current_user.role != 'buyer'
                %li= link_to 'Users', users_path
              - if merchant_current_user.role == 'owner'
                %li= link_to 'Control Center', upload_dashboards_path

          - if merchant_current_user
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "#{Date.today.strftime("%B %e, %Y")}" , "#"
              %li.dropdown
                %a.dropdown-toggle{href: '#', 'data-toggle'=>'dropdown'}
                  %span= merchant_current_user.first_name
                  %span.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Change Password', change_password_users_path
                  - if merchant_current_user.role == 'owner'
                    %li
                      = link_to 'View API Key', view_api_key_users_path
                  %li
                    = link_to 'Log Out', session_path('delete-mc-user'), method: :delete

    .view-spacer
    .container      
      - flash.each do |name, msg|
        - if name.to_s == 'notice'
          .alert.alert-info.alert-dismissable
            %button.close{ 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }
              = '&times;'.html_safe
            %strong Well done!
            = msg
        - elsif name.to_s == 'alert'
          .alert.alert-danger.alert-dismissable
            %button.close{ 'data-dismiss' => 'alert', 'aria-hidden' => 'true' }
              = '&times;'.html_safe
            %strong Oh snap!
            = msg
      .view-spacer-10{style: "display: #{'none;' if render_breadcrumbs.blank? }"}
        .col-xs-12.padding-0
          %ol.breadcrumb
            = render_breadcrumbs tag: :li, separator: ""            
      = yield
    .view-spacer
= yield :footer
:javascript
  $(function() {
    setTimeout(function() {
    $(".alert-info").fadeOut('slow');}, 3000
    );
  });  